### ISSUE TITLE
Dark theme option

### ISSUE THREAD

**Issue by falkTX** [MartinBriza/adwaita-qt#1]
Before anything, thanks for doing this!
Having a consistent look between toolkits is something I've been looking for a while (I don't like the oxygen theme very much).

Gnome/Adwaita has an option for "Global Dark Theme".
Please provide such option for this theme as well.

**Comment by MartinBriza** [comment]
Adwaita now works much better with the systemwide color settings. Now we just need to accomodate it better for the dark variant and most importantly have a way to trigger it from QGnomePlatform.

**Comment by MartinBriza** [comment]
The theme now supports a dark variant. There will be some minor fixes to it but there is now support in QGnomePlatform too. Wait for the next release (0.98 or higher), I think I'll release it this week.
