### ISSUE TITLE
[KeePassX] Text doesn't fit into entry fields

### ISSUE THREAD

**Issue by chekavy** [MartinBriza/adwaita-qt#11]
Go to `Extras menu => Settings => Security tab`

### KeePassX with Adwaita QT theme

![settings](https://cloud.githubusercontent.com/assets/10311057/7788299/392a8b52-0235-11e5-8fe2-b785f82b78f0.png)

### KeePassX without Adwaita QT theme (default Adwaita theme)

![settings-default](https://cloud.githubusercontent.com/assets/10311057/7788301/3ceba7b2-0235-11e5-930d-1e706757ff1b.png)

KeePassX 0.4.3, Fedora 22 with GNOME 3.16

**Comment by MartinBriza** [comment]
This is a duplicate issue with #10
