### ISSUE TITLE
Compile instructions?

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#13]
I'm trying to package this for the AUR since no-one seems willing to do it. I would do this happily, but I have no experience with packaging (or compiling) QT themes and I can't find any instructions either. Thanks.

**Comment by 183amir** [comment]
@DoctorJellyface thank you for packing this. Have you looked at how it is packaged in Fedora?

**Comment by DoctorJellyface** [comment]
Yes (but that's a nice URL, thanks, I got it from a package), but I don't know what `%_target_platform` nor what `%cmake` represents.

**Comment by 183amir** [comment]
I think `%_target_platform` is something like `fedora23_x64` so it's not very important. And `%{cmake}` can be replaced by just `cmake`. I have no idea, I am just guessing here.

**Comment by MartinBriza** [comment]
`cmake` is the buildsystem I use for this package. Basic setup is the usual `mkdir build; cd build; cmake ..; make; make install`. For packaging, you'll probably need to modify the variables with install target paths. These are contained in CMakeLists.txt and you can override them when running `cmake` like this: `cmake -D<variable name>:<type>=<something>`.
I'll put up some info in the afternoon into readme but don't hesitate to contact me on IRC anyway if you need help. Just please note I'll be out of the grid for about two weeks since tomorrow.

**Comment by DoctorJellyface** [comment]
Thanks for the info. I'll look more into this in the afternoon. For now, could you just tell me the builddeps? Thanks.

**Comment by 183amir** [comment]
I think adding what MartinBriza said to this would do:

	base_package_name = "adwaita-qt"
	split_packges = "adwaita-qt4" "adwait-qt5" "adwaita-qt-common"

	build(){
		cd $srcdir
		cmake
		make
	}

	package(){
		make install/fast DESTDIR=$pkgdir
	}

**Comment by MartinBriza** [comment]
It depends only on Qt5Core, Qt5Widgets and Qt5Gui. For Qt4, it's the whole main library. You also have to specify -DUSE_QT4=true if you want a Qt4 build. Notice that there are two `cmake`, two `make` and two `make install` calls in the Fedora spec file - for Qt4 and Qt5 builds respectively. The asset directory containing a few images of checkboxes and such is shared between both versions.

In regards of building, I'm not sure if what @183amir posted is proper. `cmake` without any arguments will install everyting into the `/usr/local` prefix, which is usually not expected when building a package. I'd take a look at how other `cmake`-built packages are handled in AUR.

**Comment by DoctorJellyface** [comment]
```
# $Id$
# Maintainer: Felix Yan <felixonmars@archlinux.org>
# Contributor: Andrea Scarpino <andrea@archlinux.org>
# Contributor: Antonio Rojas

pkgbase=adwaita-qt
pkgname=('adwaita-qt' 'adwaita-qt4')
pkgver=5.3.2
pkgrel=1
arch=('i686' 'x86_64')
#url='https://projects.kde.org/projects/kde/workspace/breeze'
license=('LGPL')
#makedepends=('extra-cmake-modules' 'automoc4')
source=("https://github.com/MartinBriza/adwaita-qt/archive/master.zip")
md5sums=('SKIP')

prepare() {
  mkdir build{,-qt4}
}

build() {
  cd build
  cmake ../${pkgbase}-master \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=lib \
    -DBUILD_TESTING=OFF
  make

  cd ../build-qt4
  cmake ../${pkgbase}-master \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DUSE_QT4=ON \
    -DBUILD_TESTING=OFF
  make
}

package_adwaita-qt() {
  depends=()
  pkgdesc=''
  optdepends=('adwaita-qt4: asdf')

  cd build
  make install/fast DESTDIR=$pkgdir
}

package_adwaita-qt4() {
  pkgdesc=''
  depends=()

  cd build-qt4
  make install/fast DESTDIR=$pkgdir

  # needed for pure Qt4 apps
  #install -d "$pkgdir"/usr/lib/qt4/plugins/styles
  #ln -s /usr/lib/kde4/plugins/styles/breeze.so "$pkgdir"/usr/lib/qt4/plugins/styles
}
```

I get:

```
$ makepkg -si
==> Vytváram balíček: adwaita-qt 5.3.2-1 (St júl 29 12:43:20 CEST 2015)
==> Zisťujem runtime závislosti...
==> Zisťujem buildtime závislosti...
==> Získavam zdrojové súbory...
  -> Nájdený master.zip
==> Kontrolujem zdrojové súbory pomocou md5sums...
    master.zip ... Preskočené
==> Rozbaľujem zdrojové súbory...
  -> Rozbaľujem master.zip pomocou bsdtar
==> Spúšťam prepare()...
==> Odstraňovanie existujúceho adresára $pkgdir/...
==> Spúšťam build()...
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    LIB_INSTALL_DIR


-- Build files have been written to: /home/juraj/Stavby/AUR/adwaita-qt/src/build
Scanning dependencies of target adwaita-qt5_automoc
[ 25%] Automatic moc for target adwaita-qt5
Generating moc_adwaita.cpp
Generating moc_styleplugin.cpp
[ 25%] Built target adwaita-qt5_automoc
Scanning dependencies of target adwaita-qt5
[ 50%] Building CXX object src/style/CMakeFiles/adwaita-qt5.dir/adwaita.cpp.o
/home/juraj/Stavby/AUR/adwaita-qt/src/adwaita-qt-master/src/style/adwaita.cpp:25:29: fatal error: QtGui/QSizePolicy: Adresár alebo súbor neexistuje
compilation terminated.
src/style/CMakeFiles/adwaita-qt5.dir/build.make:54: recipe for target 'src/style/CMakeFiles/adwaita-qt5.dir/adwaita.cpp.o' failed
make[2]: *** [src/style/CMakeFiles/adwaita-qt5.dir/adwaita.cpp.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/style/CMakeFiles/adwaita-qt5.dir/all' failed
make[1]: *** [src/style/CMakeFiles/adwaita-qt5.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
==> CHYBA: Chyba nastala v build().
    Prebieha rušenie...
```

BTW what are the make deps and normal deps?

**Comment by MartinBriza** [comment]
Build deps are the same as runtime deps - just Qt, basically. You probably don't have Qt5Gui in that build above.

**Comment by DoctorJellyface** [comment]
I have full Qt5.

**Comment by MartinBriza** [comment]
Hmm, try `find /usr/include -name QSizePolicy` if it locates anything. After that, please try pinging mbriza  on freenode, I think we'll settle this faster via chat.

**Comment by DoctorJellyface** [comment]
I am sorry I didn't reply last night. I suspect your already away aren't you? Well, anyway, I won't give up, we're discussing it at the [Arch linux forum](https://bbs.archlinux.org/viewtopic.php?pid=1548838#p1548838) already.

`find /usr/include -name QSizePolicy` returns:
```
$ find /usr/include -name QSizePolicy
/usr/include/qt4/QtGui/QSizePolicy
/usr/include/qt/QtWidgets/QSizePolicy
```

**Comment by DoctorJellyface** [comment]
[Tada!](https://aur4.archlinux.org/pkgbase/adwaita-qt/)

**Comment by DoctorJellyface** [comment]
If anyone wants to be a co-maintainer, just ask.
