### ISSUE TITLE
Otter browser tab bar lacks background

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#18]
The same screenshot, AGAIN:

![snimka obrazovky z 2015-09-13 14-05-38](https://cloud.githubusercontent.com/assets/7472425/9836689/1e51a856-5a23-11e5-9d4e-f58db7dd4468.png)

As you see, instead of it having a grey background, it has the same one as everything else.

**Comment by MartinBriza** [comment]
Hmm, I'll see about this. Tab backgrounds are a horrible pain to do in the Qt theming. Probably I'll switch to another look of the tabs (like the old Adwaita in <3.10 series GNOME). Not sure yet though.

**Comment by DDZ57** [comment]
« Probably I'll switch to another look of the tabs (like the old Adwaita in <3.10 series GNOME). »
Oh no! I think Qt version and Gtk'S one must be as close as possible.

**Comment by DoctorJellyface** [comment]
> Probably I'll switch to another look of the tabs (like the old Adwaita in <3.10 series GNOME). Not sure yet though.

Please don't. The tabs work fine everywhere else. Also, I think otter uses QTabBar.

**Comment by DoctorJellyface** [comment]
Fixed, with a minor issue, I'll open a new one.
