### ISSUE TITLE
Button highlights dots should be two pixels wide

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#19]
Observe:

GTK:
![snimka obrazovky z 2015-09-13 14-10-30](https://cloud.githubusercontent.com/assets/7472425/9836702/71dc0d54-5a23-11e5-9841-5cde2e69e45b.png)

Qt:
![snimka obrazovky z 2015-09-13 14-10-52](https://cloud.githubusercontent.com/assets/7472425/9836713/badd4d38-5a23-11e5-83ac-3d73b06b0959.png)

Also, the colour looks a tinge different, don't know if it's because of that.

**Comment by MartinBriza** [comment]
I don't seem to be able to mimic the shading on the dashes in GTK Adwaita.
If you're still not happy with the result, please feel free to reopen the bug and I'll see if there's anything more I can do about it.

**Comment by DoctorJellyface** [comment]
No, it seems fine, thanks!
