### ISSUE TITLE
Button corners are weird

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#20]
![snimka obrazovky z 2015-09-13 14-51-45](https://cloud.githubusercontent.com/assets/7472425/9836795/fd9ca0a8-5a26-11e5-9bd5-5a9f38bbf493.png)

Some have small grey squares in the corners and the corners themselves are different.

**Comment by MartinBriza** [comment]
I noticed this too. It affects Qt5 only though for some reason.

**Comment by DoctorJellyface** [comment]
Still has problems with the default buttons. The other are fine, thanks!

**Comment by DoctorJellyface** [comment]
OK, so this issue comes back with small buttons with focus.
