### ISSUE TITLE
Menus have a grey outline

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#21]
![otter-menu](https://cloud.githubusercontent.com/assets/7472425/10119592/6d696c18-649a-11e5-9491-e1f97aaa6cfd.png)

This gives the effect that the menus are wrongly aligned.

**Comment by MartinBriza** [comment]
Actually, it should be a darker gray color - fixed with 0bf4d0bdbe3bfe9af6ff1d2a4e1ee223e39ce44d
