### ISSUE TITLE
Secondary menus have a different highlight colour

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#22]
![otter-menu](https://cloud.githubusercontent.com/assets/7472425/10119599/8bdee218-649a-11e5-8e25-6e1c037c7152.png)

You can slightly see that there's something out of place, but if you use redshift or something like that the contrast doubles.

**Comment by MartinBriza** [comment]
Fixed with 4930be070ea7fefe5c8763c7e2fb1a483a3fd179
