### ISSUE TITLE
Background color changed (since GTK 3.16?)

### ISSUE THREAD

**Issue by DDZ57** [MartinBriza/adwaita-qt#23]
Hello!

First of all, thank you for your nice idea porting Adwaita to QT! B-)
It seems the background color isn't #EDEDED anymore since GTK 3.16 but now #E9E9E9. I could change it for GTK 2, Openbox… themes but I couldn't for QT (both 4 and 5 versions). Moreover, the same bug affects the menus background.

Can you update it, please ?
Thank you in advance and have a nice day! :-)

![background color bug](https://cloud.githubusercontent.com/assets/2294605/10215520/72880b42-6822-11e5-8b6b-d64545b07d95.png)

**Comment by MartinBriza** [comment]
Hello, thanks for letting me know! I have just updated my machine to GNOME 3.18, so I'll try to keep as up-to-date as possible. Also I'm working towards global color scheme usage, although the progress is a bit slow. But, when I'm done, at least color scheme issues should not be present anymore.

**Comment by MartinBriza** [comment]
Colors should now be taken from the system.
