### ISSUE TITLE
TreeView headers have wrong text settings

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#29]
This is from KeePassX:

![snimka obrazovky z 2015-10-03 12-51-05](https://cloud.githubusercontent.com/assets/7472425/10267243/3ab66764-6a8d-11e5-9df9-fbfdca8a72e5.png)

For comparison, this is the System Monitor:

![snimka obrazovky z 2015-10-04 11-42-17](https://cloud.githubusercontent.com/assets/7472425/10267242/3023fdac-6a8d-11e5-9c51-74e30d755811.png)

I'm not sure if the colour is my fault or not, also there should be a thicker grey bar on the top, but the text should be left aligned, not center, and bold.

Also, is it possible to actually set the font to bold? Adwaita uses bold in many places, but I haven't seen them in any Qt themes.

**Comment by MartinBriza** [comment]
Done.
