### ISSUE TITLE
Top menu bar has slight offsets

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#30]
Being the pixel perfect guy that I am, I noticed something was amiss while fixing stuff after a bad font upgrade.

It looks like in Qt5, the top menu text has padding of one pixel above and below the text more than it should, making the bar two pixels higher than it should.

In Qt4, it's offsetted by one pixel to the right.

After the cantarell upgrade it looks even worse, but I believe its it's fault.

**Comment by MartinBriza** [comment]
This should be closed by #39
