### ISSUE TITLE
Tabs in otter are a tad higher than they should

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#31]
Screenshot of otter:

![snimka obrazovky z 2015-10-07 17-21-53](https://cloud.githubusercontent.com/assets/7472425/10342847/55302e46-6d1b-11e5-8b0a-2af1213253bf.png)

Screenshot of Web:

![snimka obrazovky z 2015-10-07 16-36-11](https://cloud.githubusercontent.com/assets/7472425/10342851/5d14af4c-6d1b-11e5-95df-977a96ddb050.png)

It's a shame the tab bar is implemented in otter as it is though :|

**Comment by MartinBriza** [comment]
Hmmm, I don't know what does Otter modify in the style - from the glance I took at its source code, there doesn't seem to be anything suspicious. It looks bad though, so I'll leave this open for now to see if I can come up with a solution over time.

**Comment by MartinBriza** [comment]
The tab height is now either the same or they're one pixel off... I think that's okay.
