### ISSUE TITLE
QtCreator Menubar Problem

### ISSUE THREAD

**Issue by byECHO** [MartinBriza/adwaita-qt#34]
Menubar of QtCreator is missing. There is a small button which pops-up the menu when clicked.

![snapshot1](https://cloud.githubusercontent.com/assets/6375449/10344401/c11002fc-6d2b-11e5-890b-5d017dff0af0.png)

![snapshot2](https://cloud.githubusercontent.com/assets/6375449/10344483/247c7320-6d2c-11e5-9402-f254a4dcb4b7.png)

**Comment by MartinBriza** [comment]
Is this happening with recent revisions, please? I think this behavior occured only in one commit about a week ago, which has been fixed a few minutes after.

**Comment by byECHO** [comment]
No, It looks like it is fixed. Just once, It happened again but it is fixed by restarting.

**Comment by byECHO** [comment]
It is fixed, somewhat. If I use dark theme of QtCreator it works. But If I use default one(in pictures) it happens again.

**Comment by byECHO** [comment]
Also, I just recently installed GNOME. This problem does not occurs in GNOME only in KDE.

**Comment by hazzl** [comment]
I can confirm this issue. With current versions of adwaita-qt5 and QtCreator 4.0.2

**Comment by hazzl** [comment]
I can also confirm that this issue exists only with the light themes of QtCreator, when switching to QtCreator's "dark" theme, the issue goes away.

**Comment by grulja** [comment]
Could you please test the patch from https://github.com/MartinBriza/adwaita-qt/pull/39?

**Comment by Viterzgir** [comment]
I have same issue, patch not work for me.

**Comment by grulja** [comment]
I updated the pull request, there is one more patch to fix this issue, could you please test it?

**Comment by Viterzgir** [comment]
I've tested updated patch and problem with menubar still there. Switching to fusion style completely resolve this issue.

**Comment by grulja** [comment]
Thanks for testing. I added some debug info to the pull request so we can identify why it's still broken. You just need to run "export QT_LOGGING_RULES=adwaita-qt.debug=true" in a terminal and open QtCreator from there to see the output.

**Comment by Viterzgir** [comment]
With debug info:
![1467142685](https://cloud.githubusercontent.com/assets/19819279/16429781/3b1c6704-3d81-11e6-8650-d773a569bbfa.png)
I don't now why but no problem with menubar. Without debug info Qtcreator not show menubar properly:
![1467142380](https://cloud.githubusercontent.com/assets/19819279/16429834/7e234ebe-3d81-11e6-95cf-56de1481dda0.png)

**Comment by grulja** [comment]
There is still one remaining problem. The menubar is still too high compared to menubar from a gtk application using adwaita theme, but it's already reported here as a different bug.

**Comment by MartinBriza** [comment]
This should be fixed by #39
