### ISSUE TITLE
Style isn't found/can't be used by Skype

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#35]
If I try desktop settings, it goes with the horrible Win98-era GUI. Dunno what the problem may be.

EDIT: I can't manually select adwaita from skype either.

**Comment by MartinBriza** [comment]
You have to have the 32b version of the plugin installed. Skype is distributed that way only.

**Comment by DoctorJellyface** [comment]
Oh duh, how could I have forgotten about that. Thanks. Looks like I'll have to make a 32-bit package.
