### ISSUE TITLE
Wrong font size in Qt5 menubars

### ISSUE THREAD

**Issue by DoctorJellyface** [MartinBriza/adwaita-qt#36]
The menubars were completely fine until Cantarell `0.0.17.2`. It still works correctly in Qt4 apps.

Qupzilla (Qt5):

![snimka obrazovky z 2015-12-05 16-32-56](https://cloud.githubusercontent.com/assets/7472425/11608595/fc2ac2f8-9b6d-11e5-9e76-c4bb9b14c9af.png)

Liferea (Gtk3):

![snimka obrazovky z 2015-12-05 16-33-14](https://cloud.githubusercontent.com/assets/7472425/11608597/09aba9f6-9b6e-11e5-9824-7f03c6cf53ab.png)

**Comment by MartinBriza** [comment]
I think font sizes are changed outside of the theme. We'll look at this furter so we're sure but it's likely this would be changed using a Qt platform theme.

**Comment by MartinBriza** [comment]
I think this is OK now. Please reopen the issue if it happens again.
