### ISSUE TITLE
Spin Box controls too large

### ISSUE THREAD

**Issue by dsboger** [MartinBriza/adwaita-qt#37]
The "-" and "+" buttons in the spin box are too large, often hiding the text entry.

Screenshot of the large spin box (qt5ct preview window):
![spinbox_large](https://cloud.githubusercontent.com/assets/2356842/13184561/c3db353a-d723-11e5-8e55-3701cb06ac29.png)

**Comment by neildarlow** [comment]
If you look at the size of the + and - buttons in comparison with other elements of the theme they are to the same scale.

The real problem is that Qt native controls place the + and - buttons above each other while GT3 controls place them adjacent. This is a fundamental design difference.

The sizing appears to be overall and the text area shrinks as a result. If the application cannot dynamically adjust for the difference (I don't program Qt but I assume it has dynamic padding controls) then this is what you get.

In this situation I use the Qt Fusion style. It provides native QSpinBox and similar control functionality.

**Comment by rokm** [comment]
The adwaita theme for Qt appears to be dynamically deciding whether to render spin box buttons as two small buttons stacked on top of each other, or two large, side-by-side buttons.

However, the decision as to when to switch from one to another appears to be based on incorrect computation, which does not account for the contents of the spin box. Specifically, consider the line 
1418 in adwaita.cpp:
```
if (opt->rect.width() < opt->rect.height() * 2.4 + 16) {
```

This check effectively ensures only that the spin box control is wide enough to put inside two buttons (1.2*height each). The extra 16 pixels are not guaranteed to accommodate the rest of the contents, and consequently the large buttons tend to get drawn over the contents.

Minimal working example:
```
#include <QtWidgets>

int main (int argc, char **argv)
{
    QApplication app(argc, argv);

    QWidget window;
    window.setWindowTitle("Spin box test");

    QGridLayout *layout = new QGridLayout();
    window.setLayout(layout);

    QSpinBox spinBox;
    spinBox.setRange(0, 9999999);
    spinBox.setValue(1000);
    layout->addWidget(&spinBox);

    window.show();

    return app.exec();
}
```

Result:
![spinbox-size-example](https://cloud.githubusercontent.com/assets/5579125/17002092/17e4dafa-4eca-11e6-8224-916cf85e1b80.png)

There are three ways to fix this:
A) always use the small buttons (and add their proper size in Adwaita::sizeFromContents() in line 1702.
B) always use the large buttons (and add their proper size; same as above)
C) account for the width of contents using current font metrics, and dynamically determine type of buttons to use

The drawback of C) is that the spin box controls may change as the value changes. Also, an additional inconsistency with Qt's gtk style is that in the latter, the space allocated for spin box content seems to depend on its range (effectively, the size is computed for minimum and maximum value, and the larger one is used). I think the Gtk version of adwaita does the same... But as far as I can tell from cursory glance, there is no easy way to get this information inside Adwaita::subControlRect, where we would need it to dynamically switch between the control sizes.

I suppose B) would be a viable option, as it seems that the Gtk version of adwaita always uses the large buttons by default?
