### ISSUE TITLE
Grey area under custom tabbar in qutebrowser

### ISSUE THREAD

**Issue by The-Compiler** [MartinBriza/adwaita-qt#45]
I'm the developer of [qutebrowser](https://github.com/The-Compiler/qutebrowser), which has a heavily customized [tabbar](https://github.com/The-Compiler/qutebrowser/blob/v0.8.2/qutebrowser/mainwindow/tabwidget.py#L238-L508) with a [custom style](https://github.com/The-Compiler/qutebrowser/blob/v0.8.2/qutebrowser/mainwindow/tabwidget.py#L515-L731).

With adwaita-qt5, this appears under the tabbar:

![adwaita](https://cloud.githubusercontent.com/assets/625793/17833183/49a1ec5e-6716-11e6-8ec9-2973407a346e.png)

It's colored according to `QPalette::Window`.

I've tried various things in my style to make it go away, without any luck so far, so I'd appreciate some help!

**Comment by MartinBriza** [comment]
This is now fixed. Thanks for the report.
