### ISSUE TITLE
Tabs have too much padding, not enough space for text

### ISSUE THREAD

**Issue by mitya57** [MartinBriza/adwaita-qt#49]
Look at the two attached screenshots of Qt Assistant: first with Adwaita, second with Fusion. Width of the tabs is the same, but Adwaita is not able to display the text on the tabs. Instead of (at least) “Bookma…”, it shows only “Bo…”, which is not very informative.

It is the default configuration of Qt Assistant window.

![adwaita](https://cloud.githubusercontent.com/assets/1381584/18411011/aeb1cf6e-777f-11e6-9d56-f3875c9f179f.png) ![fusion](https://cloud.githubusercontent.com/assets/1381584/18411012/aeb608cc-777f-11e6-8910-3bc870b3cd74.png)

**Comment by MartinBriza** [comment]
This is now fixed in master
