### ISSUE TITLE
Don't show pushbutton and menu icons under GNOME

### ISSUE THREAD

**Issue by CDrummond** [MartinBriza/adwaita-qt#55]
When run under GNOME, applications should not show icons on pushbuttons, or menus - this can be enforced by Adwaita Qt

**Comment by mitya57** [comment]
It looks like 39138b7df8111576e264eabee78656322459cb2e needs to be re-applied.

**Comment by MartinBriza** [comment]
whoops, sorry for reintroducing this problem

**Comment by jp7677** [comment]
@MartinBriza Any chance to disable icons on menus as well as the original author stated?
PS: Thank you so much for your work here, having the same style on gtk and qt app makes gnome so much more beautiful.
