### ISSUE TITLE
adwaita-qt causes a graphical issue in the menubar of mGBA

### ISSUE THREAD

**Issue by MartinBriza** [MartinBriza/adwaita-qt#59]
Copied from MartinBriza/QGnomePlatform#22 :

@darkgallium
> Hi, 
>
> I'm using a GBA emulator using Qt 5 called mGBA on Fedora 25,
> QGnomePlatform, which is shipped by default since this release, causes this weird graphical artifact on mGBA 
> ![mgba_qt_issue](https://cloud.githubusercontent.com/assets/17528199/22619695/aab23e3c-eafa-11e6-849e-ac90d618ebd8.png)
> When I remove QGnomePlatform, this bug disappears. 
> According to one developer of mGBA (mgba-emu/mgba#514), the problem needs to be fixed upstream.
>
> Do you think it is possible to fix it on your side ?

Confirmed this bug is related to adwaita.

**Comment by darkgallium** [comment]
Thank you for your responsiveness :)
I'm sorry but I can't find the issue tracker for the Breeze theme, do you know where it is ?

**Comment by MartinBriza** [comment]
In the KDE bugtracker

**Comment by darkgallium** [comment]
Issue opened on the KDE bugtracker : https://bugs.kde.org/show_bug.cgi?id=376105

**Comment by darkgallium** [comment]
Just so you know, issue was not solved by version 0.98 revision 1 of adwaita-qt.

**Comment by MartinBriza** [comment]
Still broken to me to be honest. I'm going to look at it soon though.

2017-03-09 22:03 GMT+01:00 darkgallium <notifications@github.com>:
