### ISSUE TITLE
[KeePassX] Missing checkboxes icons for menu

### ISSUE THREAD

**Issue by chekavy** [MartinBriza/adwaita-qt#8]
### KeePassX with Adwaita QT theme

![menu-checkboxes](https://cloud.githubusercontent.com/assets/10311057/7788184/946f834a-0231-11e5-90e9-016b76013a8a.png)

### KeePassX without Adwaita QT theme (default Adwaita theme)

![menu-checkboxes-default](https://cloud.githubusercontent.com/assets/10311057/7788185/95997884-0231-11e5-9840-12b004eaa845.png)

KeePassX 0.4.3, Fedora 22 with GNOME 3.16

**Comment by arbitrary-dev** [comment]
+1

**Comment by MartinBriza** [comment]
Hmm, strange, I specifically remember adding this feature. Thanks for reporting, will look into it!

**Comment by arbitrary-dev** [comment]
Still not working for goldendict and puddletag apps.
