### ISSUE TITLE
Instructions in README.md seem out of date

### ISSUE THREAD

**Issue by rrthomas** [MartinBriza/adwaita-qt#85]
As suggested, on my 64-bit system I used:

    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLIB_SUFFIX=64 ..

and got the warning:

    CMake Warning:
      Manually-specified variables were not used by the project:
    
        LIB_SUFFIX

Using the 0.98 release.

**Comment by MartinBriza** [comment]
Oh, you're right, thanks for pointing that out.

**Comment by rrthomas** [comment]
(Also applies to git master HEAD, which I tried before the release.)
