### ISSUE TITLE
Build fails with `add_subdirectory given source "style" which is not an existing directory.` message

### ISSUE THREAD

**Issue by AnwarShah** [MartinBriza/adwaita-qt#88]
I used this command following the readme to build it
`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr`

Note that, I had to copy the `CMakeLists.txt` file to `build` directory.

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:49 (add_subdirectory):
  add_subdirectory given source "style" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/home/anwar/Apps/Sources/adwaita-qt-0.98/build/CMakeFiles/CMakeOutput.log".

**Comment by AnwarShah** [comment]
The issue is gone when I try to build from the root directory without `cd`int to the build directory. Now successfully installed. The readme should be corrected.

**Comment by MartinBriza** [comment]
Oh my, I deleted the two dots that make it take the CMakeLists.txt from the parent directory. Sorry for that, the README is wrong.

**Comment by AnwarShah** [comment]
Nice to know it's fixed. Thanks for the project. Can we have anything for the window decoration yet? I got one in kde store, but it's only light version.

**Comment by MartinBriza** [comment]
I'm planning to work on at least a Wayland window decoration. KDecoration may be a possibility but Wayland will come first.
