### ISSUE TITLE
[KeePassX] ProgressBar doesn't fill for Password Generator

### ISSUE THREAD

**Issue by chekavy** [MartinBriza/adwaita-qt#9]
Go to `Extras menu => Password Generator`

### KeePassX with Adwaita QT theme

![passwordgenerator-progressbar](https://cloud.githubusercontent.com/assets/10311057/7788234/e54aed08-0232-11e5-8a4c-58639f3c15ca.png)

### KeePassX without Adwaita QT theme (default Adwaita theme)

![passwordgenerator-progressbar-default](https://cloud.githubusercontent.com/assets/10311057/7788235/ea18f262-0232-11e5-8f42-64608fe7f1ac.png)

KeePassX 0.4.3, Fedora 22 with GNOME 3.16

**Comment by MartinBriza** [comment]
Should be fixed in a38a5e3
