### ISSUE TITLE
Menus have no border or shadow

### ISSUE THREAD

**Issue by Pointedstick** [MartinBriza/adwaita-qt#92]
I'm using this theme in KDE Plasma 5, compiled from the latest git master. It's very nice, except for one issue: menus don't have a border or shadow of any kind, making them look weird when opened, like they're trying to blend into the content. Here's what it looks like in Dolphin:

![dolphin_with_weird_menu](https://cloud.githubusercontent.com/assets/1097249/25305991/30d71df6-2742-11e7-9bf9-620b7c60b7b3.png)

**Comment by MartinBriza** [comment]
Hey,
thanks for the report. Yeah, I removed the borders a few days ago because they're added by the window manager in GNOME. We should find a way to make kwin draw them too or just detect that the theme is not used in GNOME and paint some border ourselves...

**Comment by Pointedstick** [comment]
Tested; confirmed that menus now have borders. How about shadows?

**Comment by MartinBriza** [comment]
Honestly, I think the borders are fine for now. You can reopen this if you
think having shadows is an important and I'll think about it in the future.
However, I think there are more important bugs and features lying ahead, so
it'll take me a while but at the same time it's pretty possible someone
else will fix this behavior.

2017-05-26 15:46 GMT+02:00 Nate Graham <notifications@github.com>:
