### ISSUE TITLE
Question - Dark theme Fedora 26

### ISSUE THREAD

**Issue by nill14** [MartinBriza/adwaita-qt#96]
![screenshot from 2017-07-10 12-58-24](https://user-images.githubusercontent.com/2973391/28012778-8de66f2c-656f-11e7-9ed4-d899b88c4fb6.png)
I wonder why dark theme doesn't work for me. I followed the video shown in https://eischmann.wordpress.com/2017/02/10/dark-adwaita-and-highcontrast-themes-for-qt/
Do I need to install any package or so?

**Comment by 0mark** [comment]
I might have a similar problem. When i setthe dark adwaita variant and start (some) applications, mostly the light theme is used, except for some fonts where the dark theme is used (leading to light-white text on dark-white background).
As a sidenote: When i launch qt5ct and change the theme while a qt5 application is running, the dark adwaita theme is suddenly used, but only until i end said application.

**Comment by nill14** [comment]
ok, after 
dnf install qgnomeplatform
echo QT_QPA_PLATFORMTHEME=qgnomeplatform > /etc/environment
I get at least something resembling at least adwaita (light). 
Why do I need to install qgnomeplatform manually? Why is environment not set (https://github.com/GNOME/gnome-session/commit/971baf2e225abc5a)? How do I get dark theme, please?

**Comment by MartinBriza** [comment]
It depends on the version of QGnomePlatform you have. This landed in 0.3. In Fedora, it should be there by default.
Now, you don't have to set QT_QPA_PLATFORMTHEME manually. QGnomePlatform overrides the "gnome" platformtheme that's included in upstream Qt. However, you still have to install it manually (it's included in the default Fedora Workstation install though).
I'll close this issue as it's not really related to Adwaita, however please keep asking questions or raising concerns if there's something unclear, I'll be happy to answer them (and now much sooner than this time - sorry for taking so long).
